version: "3.7"
services:
  db:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: wordpress
      MYSQL_USER: saimon
      MYSQL_PASSWORD: 1111
  wp:
    container_name: wordpress
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: saimon
      WORDPRESS_DB_PASSWORD: 1111
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
    volumes:
      ["./:/var/www/html"]
  wpcli:
    container_name: wpcli
    depends_on:
      - db
      - wp
    image: wordpress:cli
    # This is required to run wordpress-cli with the same
    # user-id as wordpress. This way there are no permission problems
    # when running the cli
    user: xfs
    volumes:
      ["./:/var/www/html"]
    links:
      - db
    entrypoint: wp
    command: "--info"

volumes:
  db_data: